apiVersion: v1
kind: Service
metadata:
  name: service-example
  labels:
    application: deployment-example
spec:
  type: LoadBalancer
  selector:
    application: deployment-example
  ports:
   - name: frontend
     port: 80
     targetPort: 80
     protocol: TCP